In [20]:
import numpy as np
M = np.array([[0.06,0.22,-0.22,0.08],[0.22,1.12,-0.08,0.25],[-0.22,-0.08,1.12,-0.25],[0.08,0.25,-0.25,2.04]])
print(M)
eige,eigv=np.linalg.eigh(M)
print(eigv)
print(eigv[:,3]**2)

[[ 0.06  0.22 -0.22  0.08]
 [ 0.22  1.12 -0.08  0.25]
 [-0.22 -0.08  1.12 -0.25]
 [ 0.08  0.25 -0.25  2.04]]
[[ 9.68595036e-01 -3.98854639e-16 -2.32624857e-01  8.78028031e-02]
 [-1.75781313e-01  7.07106781e-01 -6.35570582e-01  2.55246872e-01]
 [ 1.75781313e-01  7.07106781e-01  6.35570582e-01 -2.55246872e-01]
 [ 5.05141313e-03  4.71844785e-16  3.71464327e-01  9.28433485e-01]]
[0.00770933 0.06515097 0.06515097 0.86198874]
